<?php

namespace Vkoori\JwtAuth\Providers;

use Illuminate\Support\Str;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Auth;
use Vkoori\JwtAuth\Auth\JwtAuthGuard;
use Illuminate\Foundation\Application;
use Vkoori\JwtAuth\Auth\JwtAuthProvider;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->mergeConfigFrom(__DIR__ . '/../config/jwt-guard.php', 'jwt-guard');
    }

    public function boot(): void
    {
        // publish configs
        $this->publishes([
            __DIR__ . '/../config/jwt-guard.php' => config_path('jwt-guard.php'),
        ], 'config');

        if (config('jwt-guard.jwt.set_cookie')) {
            $router = $this->app->make(Router::class);
            $router->pushMiddlewareToGroup('api', AddQueuedCookiesToResponse::class);
        }

        // custom guard
        Auth::extend('jwt-auth', function (Application $app, string $name, array $config) {
            return new JwtAuthGuard(
                Auth::createUserProvider($config['provider']),
                $app->make('request')
            );
        });

        // custom auth provider
        Auth::provider('jwt-auth-provider', function (Application $app, array $config) {
            return new JwtAuthProvider($config['model']);
        });

        // extend Str
        Str::macro('wildcard', function ($url) {
            $purl = parse_url($url);
            $host = strtolower($purl['host']);

            $valid_tlds = [
                '.local',
                '.ab.ca',
                '.bc.ca',
                '.mb.ca',
                '.nb.ca',
                '.nf.ca',
                '.nl.ca',
                '.ns.ca',
                '.nt.ca',
                '.nu.ca',
                '.on.ca',
                '.pe.ca',
                '.qc.ca',
                '.sk.ca',
                '.yk.ca',
                '.com.cd',
                '.net.cd',
                '.org.cd',
                '.com.ch',
                '.net.ch',
                '.org.ch',
                '.gov.ch',
                '.co.ck',
                '.ac.cn',
                '.com.cn',
                '.edu.cn',
                '.gov.cn',
                '.net.cn',
                '.org.cn',
                '.ah.cn',
                '.bj.cn',
                '.cq.cn',
                '.fj.cn',
                '.gd.cn',
                '.gs.cn',
                '.gz.cn',
                '.gx.cn',
                '.ha.cn',
                '.hb.cn',
                '.he.cn',
                '.hi.cn',
                '.hl.cn',
                '.hn.cn',
                '.jl.cn',
                '.js.cn',
                '.jx.cn',
                '.ln.cn',
                '.nm.cn',
                '.nx.cn',
                '.qh.cn',
                '.sc.cn',
                '.sd.cn',
                '.sh.cn',
                '.sn.cn',
                '.sx.cn',
                '.tj.cn',
                '.xj.cn',
                '.xz.cn',
                '.yn.cn',
                '.zj.cn',
                '.com.co',
                '.edu.co',
                '.org.co',
                '.gov.co',
                '.mil.co',
                '.net.co',
                '.nom.co',
                '.com.cu',
                '.edu.cu',
                '.org.cu',
                '.net.cu',
                '.gov.cu',
                '.inf.cu',
                '.gov.cx',
                '.edu.do',
                '.gov.do',
                '.gob.do',
                '.com.do',
                '.org.do',
                '.sld.do',
                '.web.do',
                '.net.do',
                '.mil.do',
                '.art.do',
                '.com.dz',
                '.org.dz',
                '.net.dz',
                '.gov.dz',
                '.edu.dz',
                '.asso.dz',
                '.pol.dz',
                '.art.dz',
                '.com.ec',
                '.info.ec',
                '.net.ec',
                '.fin.ec',
                '.med.ec',
                '.pro.ec',
                '.org.ec',
                '.edu.ec',
                '.gov.ec',
                '.mil.ec',
                '.com.ee',
                '.org.ee',
                '.fie.ee',
                '.pri.ee',
                '.eun.eg',
                '.edu.eg',
                '.sci.eg',
                '.gov.eg',
                '.com.eg',
                '.org.eg',
                '.net.eg',
                '.mil.eg',
                '.com.es',
                '.nom.es',
                '.org.es',
                '.gob.es',
                '.edu.es',
                '.com.et',
                '.gov.et',
                '.org.et',
                '.edu.et',
                '.net.et',
                '.biz.et',
                '.name.et',
                '.info.et',
                '.co.fk',
                '.org.fk',
                '.gov.fk',
                '.ac.fk',
                '.nom.fk',
                '.net.fk',
                '.tm.fr',
                '.asso.fr',
                '.nom.fr',
                '.prd.fr',
                '.presse.fr',
                '.com.fr',
                '.gouv.fr',
                '.com.ge',
                '.edu.ge',
                '.gov.ge',
                '.org.ge',
                '.mil.ge',
                '.net.ge',
                '.pvt.ge',
                '.co.gg',
                '.net.gg',
                '.org.gg',
                '.com.gi',
                '.ltd.gi',
                '.gov.gi',
                '.mod.gi',
                '.edu.gi',
                '.org.gi',
                '.com.gn',
                '.ac.gn',
                '.gov.gn',
                '.org.gn',
                '.net.gn',
                '.com.gr',
                '.edu.gr',
                '.net.gr',
                '.org.gr',
                '.gov.gr',
                '.com.hk',
                '.edu.hk',
                '.gov.hk',
                '.idv.hk',
                '.net.hk',
                '.org.hk',
                '.com.hn',
                '.edu.hn',
                '.org.hn',
                '.net.hn',
                '.mil.hn',
                '.gob.hn',
                '.iz.hr',
                '.from.hr',
                '.name.hr',
                '.com.hr',
                '.com.ht',
                '.net.ht',
                '.firm.ht',
                '.shop.ht',
                '.info.ht',
                '.pro.ht',
                '.adult.ht',
                '.org.ht',
                '.art.ht',
                '.pol.ht',
                '.rel.ht',
                '.asso.ht',
                '.perso.ht',
                '.coop.ht',
                '.med.ht',
                '.edu.ht',
                '.gouv.ht',
                '.gov.ie',
                '.co.in',
                '.firm.in',
                '.net.in',
                '.org.in',
                '.gen.in',
                '.ind.in',
                '.nic.in',
                '.ac.in',
                '.edu.in',
                '.res.in',
                '.gov.in',
                '.mil.in',
                '.ac.ir',
                '.co.ir',
                '.gov.ir',
                '.net.ir',
                '.org.ir',
                '.sch.ir',
                '.gov.it',
                '.co.je',
                '.net.je',
                '.org.je',
                '.edu.jm',
                '.gov.jm',
                '.com.jm',
                '.net.jm',
                '.com.jo',
                '.org.jo',
                '.net.jo',
                '.edu.jo',
                '.gov.jo',
                '.mil.jo',
                '.co.kr',
                '.or.kr',
                '.com.kw',
                '.edu.kw',
                '.gov.kw',
                '.net.kw',
                '.org.kw',
                '.mil.kw',
                '.edu.ky',
                '.gov.ky',
                '.com.ky',
                '.org.ky',
                '.net.ky',
                '.org.kz',
                '.edu.kz',
                '.net.kz',
                '.gov.kz',
                '.mil.kz',
                '.com.kz',
                '.com.li',
                '.net.li',
                '.org.li',
                '.gov.li',
                '.gov.lk',
                '.sch.lk',
                '.net.lk',
                '.int.lk',
                '.com.lk',
                '.org.lk',
                '.edu.lk',
                '.ngo.lk',
                '.soc.lk',
                '.web.lk',
                '.ltd.lk',
                '.assn.lk',
                '.grp.lk',
                '.hotel.lk',
                '.com.lr',
                '.edu.lr',
                '.gov.lr',
                '.org.lr',
                '.net.lr',
                '.org.ls',
                '.co.ls',
                '.gov.lt',
                '.mil.lt',
                '.gov.lu',
                '.mil.lu',
                '.org.lu',
                '.net.lu',
                '.com.lv',
                '.edu.lv',
                '.gov.lv',
                '.org.lv',
                '.mil.lv',
                '.id.lv',
                '.net.lv',
                '.asn.lv',
                '.conf.lv',
                '.com.ly',
                '.net.ly',
                '.gov.ly',
                '.plc.ly',
                '.edu.ly',
                '.sch.ly',
                '.med.ly',
                '.org.ly',
                '.id.ly',
                '.co.ma',
                '.net.ma',
                '.gov.ma',
                '.org.ma'
            ];

            $tld_regex = '#(.*?)([^.]+)(' . implode('|', array_map('preg_quote', $valid_tlds)) . ')$#';

            preg_match($tld_regex, $host, $matches);
            if (!empty($matches) && sizeof($matches) > 2) {
                $extension = array_pop($matches);
                $tld = array_pop($matches);
                return '.' . $tld . $extension;
            } else {
                return '.' . $host;
            }
        });
    }
}
